# i.MX6ULL ARM cross-compile Makefile

# Cross compiler
CROSS_COMPILE = arm-linux-gnueabihf-
CC = $(CROSS_COMPILE)gcc
SQLITE_ROOT = ./sqlite_arm_lib/sqlite3-arm

CFLAGS = -Wall -Wextra -std=c11 \
         -I. \
         -I$(SQLITE_ROOT)/include

LDFLAGS = -L$(SQLITE_ROOT)/lib \
          -lsqlite3 \
          -lpthread
TARGET = tcp_sqlite_server_arm
SRCS = \
	app/main.c \
	core/gateway.c \
	transport/tcp/tcp_server.c \
	protocol/tcp/tcp_parser.c \
	service/sensor_service.c \
	service/data_service.c \
	storage/sqlite/sqlite_db.c \
	utils/log/log.c
OBJS = $(SRCS:.c=.o)
.PHONY: all clean

all: $(TARGET)
$(TARGET): $(OBJS)
	$(CC) $(OBJS) -o $@ $(LDFLAGS)


%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@


clean:
	rm -f $(OBJS)
	rm -f $(TARGET)